[package]
name = "easy_store"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A simple flash storage format for embedded systems"
repository = "https://github.com/orztrickster/easy_store"
authors = ["Yun-De Huang <startime_electronics@orztrickster.com>"]

[features]
default = []

esp = [
  "dep:esp-hal",
  "dep:esp-storage",
  "dep:esp-println",
]

esp32   = ["esp", "esp-storage/esp32",   "esp-println/esp32"]
esp32c3 = ["esp", "esp-storage/esp32c3", "esp-println/esp32c3"]
esp32c6 = ["esp", "esp-storage/esp32c6", "esp-println/esp32c6"]

[dependencies]
embedded-storage = "0.3.0"

esp-hal = { version = "~1.0", features = ["unstable"], optional = true }
esp-storage = { version = "0.5", optional = true }
esp-println = { version = "0.12", optional = true }

[profile.dev.package.esp-storage]
opt-level = 3

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false