[package]
edition      = "2024"
name         = "esp32"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "esp32"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1", features = ["esp32"] }
easy_store = { path = "../..", features = ["esp32"] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }

critical-section = "1.2.0"

esp-println = { version = "0.12", features = ["esp32"] }
esp-alloc = { version = "0.10.0" }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false

[profile.dev.package.esp-storage]
opt-level = 3